### ISSUE TITLE
Session times out too fast

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/realities#131]
Login sessions at http://realities.blivande.com/ time out very quickly right now, probably less than 15 minutes. When this happens I need to reload and then click Login again.

**Comment by Powersource** [comment]
That's weird, is it messing up refreshing the token or something? This would hopefully be fixed by https://github.com/Edgeryders-Participio/realities/issues/132 but idk.

I cranked up the "Access Token Lifespan" in keycloak to an hour, hopefully that should improve stuff in the meantime. NOTE TO SELF: UNCRANK LATER.

**Comment by aerugo** [comment]
As of right now, it is still happening, so the cranking up does not seem to have done the trick.

**Comment by Powersource** [comment]
Lol I apparently changed it for dreams instead... should be the correct one now

**Comment by Powersource** [comment]
Might have been fixed now that I merged https://github.com/Edgeryders-Participio/realities/pull/133 , we'll see how it holds up

**Comment by Powersource** [comment]
un-cranked now, hopefully oidc-react actually refreshes it

**Comment by Powersource** [comment]
I guess same issue but more specific https://github.com/Edgeryders-Participio/realities/issues/151
